name: authentication_repository
description: Dart package which manages the authentication domain.
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"
dependencies:
  cache:
    path: ../cache
  equatable: 
  http:
  firebase_auth:
  firebase_core:
  flutter:
    sdk: flutter
  google_sign_in:
  freezed_annotation:
  injectable:
  get_it:
  dartz: 
  meta:
  very_good_analysis:
  user_repository:
    path: ../user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail:
  freezed: 
  build_runner:
  injectable_generator: